#!/bin/bash

##### In order to make this work, you need a access token and refresh token
##### Get them here: https://developer.spotify.com/documentation/general/guides/authorization-guide/
##### Put them in a .env file with the variables SPOTIFY_ACCESS_TOKEN=XXXXXXXXXX and SPOTIFY_REFRESH_TOKEN=XXXXXXXXXX

if [ -f .env ]; then
        export $(cat .env | sed 's/#.*//g' | xargs)
fi

function selectPlaylist() {
        # include here all listed playlists inside of this function below
        selection=(Worship Elektro Guitar)
        # when no argument for a playlist is passed into this function, it will randomly select one
        input=$1
        if [ -z "$1" ]; then
                input=${selection[$RANDOM % ${#selection[@]}]}
        fi
        if [[ "$input" = "Worship" ]]; then
                user="f7f7f"
                playlist="2NFqwWx2Oo5PBGmfDmbUGE"
        fi

        if [[ "$input" = "Elektro" ]]; then
                user="f7f7f"
                playlist="1kQ77NTW6LN1xKJI8a8rlJ"
        fi

        if [[ "$input" = "Guitar" ]]; then
                user="f7f7f"
                playlist="2Wn8mZPx5ptRI6RH8Vrax6"
        fi
}

function updateToken() {
        if test ! -f "./token"; then
                echo $(curl -H "Authorization: Basic $SPOTIFY_ACCESS_TOKEN" -d grant_type=refresh_token -d refresh_token=$SPOTIFY_REFRESH_TOKEN https://accounts.spotify.com/api/token | jq -r '.access_token') >./token
                echo "Created new token file"
        fi
        if test $(find "./token" -mmin +59); then
                echo $(curl -H "Authorization: Basic $SPOTIFY_ACCESS_TOKEN" -d grant_type=refresh_token -d refresh_token=$SPOTIFY_REFRESH_TOKEN https://accounts.spotify.com/api/token | jq -r '.access_token') >./token
                echo "Updated token"
        fi
}

function connectAirplay() {
        ausschluss=("Apple TV (Wohnzimmer)" Computer) # add here airplay devices by name that you want to exclude from syncing music
        lautsprecher=$(curl -X GET $HOST_IP:3689/api/outputs | jq '.outputs')
        for i in $(echo "${lautsprecher}" | jq -r '.[] | @base64'); do
                _jq() {
                        echo ${i} | base64 --decode | jq -r ${1}
                }
                if [[ ! " ${ausschluss[@]} " =~ " $(_jq '.name') " ]]; then
                        if [ "$(_jq '.selected')" = false ]; then
                                echo "Switching on $(_jq '.name')"
                                curl -X PUT $HOST_IP:3689/api/outputs/$(_jq '.id')/toggle
                                sleep .5
                        fi
                fi
        done
}

if [[ "$1" = "continue" ]]; then

        # Check if Token is new enough
        updateToken
        # Read token from file
        token=$(<./token)
        # Check connection to spotify and whats currently playing
        response=$(curl -X GET "https://api.spotify.com/v1/me/player" -H "Accept: application/json" -H "Authorization: Bearer $token") 
        # uncomment to debug
        # echo $response
        whatsPlaying=$(curl -X GET "https://api.spotify.com/v1/me/player" -H "Accept: application/json" -H "Authorization: Bearer $token" | jq -r '.currently_playing_type')

        # Selecting the Raspotify device with name "Spotify-Smart-Home"
        device=$(curl -X GET "https://api.spotify.com/v1/me/player/devices" -H "Accept: application/json" -H "Authorization: Bearer $token" | jq -r '.devices[] | select(.name == "Spotify-Smart-Home") | .id')
        echo "hier" $device
        # Adding all available Airplay devices
        connectAirplay

        # if return is null
        if [ -z "$whatsPlaying" ]; then
                echo "Response empty - no song to continue - $whatsPlaying - playing random Playlist"
                selectPlaylist
                # determining a random song to start with
                lengthPlaylist=$(curl -X GET "https://api.spotify.com/v1/users/${user}/playlists/${playlist}" -H "Accept: application/json" -H "Authorization: Bearer $token" | jq -r '.tracks | select(.total) | .total') >/dev/null 2>&1
                max=$lengthPlaylist
                DIV=$((max + 1))
                R=$(($RANDOM % $DIV))
                echo "Starting Playlist $input"
                # starting the playlist, activating shuffle and playlist repeat
                curl -X PUT "https://api.spotify.com/v1/me/player/play?device_id=${device}" -H "Accept: application/json" -H "Authorization: Bearer $token" -H "Content-Type: application/json" --data "{\"context_uri\":\"spotify:user:${user}:playlist:${playlist}\",\"offset\":{\"position\":$R}}" >/dev/null 2>&1
                curl -X PUT "https://api.spotify.com/v1/me/player/volume?volume_percent=100" -H "Accept: application/json" -H "Authorization: Bearer $token" >/dev/null 2>&1
                curl -X PUT "https://api.spotify.com/v1/me/player/shuffle?state=true" -H "Accept: application/json" -H "Authorization: Bearer $token" >/dev/null 2>&1
                curl -X PUT "https://api.spotify.com/v1/me/player/repeat?state=context" -H "Accept: application/json" -H "Authorization: Bearer $token" >/dev/null 2>&1
                exit
        fi

        # Checking if playlist has been given as input to play, then this playlist is played and program is exiting
        if [[ "$2" = "playlist" ]]; then
                if [ ! -z "$3" ]; then
                        echo "zusätzlicher Input vorhanden"
                        input=$3
                fi
                selectPlaylist $input
                # determining a random song to start with
                lengthPlaylist=$(curl -X GET "https://api.spotify.com/v1/users/${user}/playlists/${playlist}" -H "Accept: application/json" -H "Authorization: Bearer $token" | jq -r '.tracks | select(.total) | .total')
                max=$lengthPlaylist
                DIV=$((max + 1))
                R=$(($RANDOM % $DIV))
                echo "Starting Playlist $input"

                # starting the playlist, activating shuffle and playlist repeat
                curl -X PUT "https://api.spotify.com/v1/me/player/play?device_id=${device}" -H "Accept: application/json" -H "Authorization: Bearer $token" -H "Content-Type: application/json" --data "{\"context_uri\":\"spotify:user:${user}:playlist:${playlist}\",\"offset\":{\"position\":$R}}" >/dev/null 2>&1
                curl -X PUT "https://api.spotify.com/v1/me/player/volume?volume_percent=100" -H "Accept: application/json" -H "Authorization: Bearer $token" >/dev/null 2>&1
                curl -X PUT "https://api.spotify.com/v1/me/player/shuffle?state=true" -H "Accept: application/json" -H "Authorization: Bearer $token" >/dev/null 2>&1
                curl -X PUT "https://api.spotify.com/v1/me/player/repeat?state=context" -H "Accept: application/json" -H "Authorization: Bearer $token" >/dev/null 2>&1
                exit
        fi

        # Checking whether music is already playing
        #curl -X GET "https://api.spotify.com/v1/me/player" -H "Accept: application/json" -H "Authorization: Bearer $token"
        spielt=$(curl -X GET "https://api.spotify.com/v1/me/player" -H "Accept: application/json" -H "Authorization: Bearer $token" | jq -r '.is_playing')

        # If result is yes, then just switching to the selected device "Spotify-Smart-Home"
        if [[ "$spielt" = "true" ]]; then
                echo "Continue current playback, just switching device"
                curl -X PUT "https://api.spotify.com/v1/me/player" --data "{\"device_ids\":[\"${device}\"]}" -H "Accept: application/json" -H "Content-Type: application/json" -H "Authorization: Bearer $token"
                exit
        fi
        # If no music is playing, continuing music - rapid succession of commands error-prone therefore, small sleep in between
        echo "Track selected but paused, will continue"
        curl -X PUT "https://api.spotify.com/v1/me/player" --data "{\"device_ids\":[\"${device}\"]}" -H "Accept: application/json" -H "Content-Type: application/json" -H "Authorization: Bearer $token"
        sleep .1
        curl -X PUT "https://api.spotify.com/v1/me/player/volume?volume_percent=100" -H "Accept: application/json" -H "Authorization: Bearer $token"
        sleep .1
        curl -X PUT "https://api.spotify.com/v1/me/player/play?device_id=${device}" -H "Accept: application/json" -H "Authorization: Bearer $token" -H "Content-Type: application/json" -H "Content-Length: 0"
        sleep .1
fi

if [[ "$1" = "stop" ]]; then

        # Check if Token is new enough
        updateToken
        # Read token from file
        token=$(<./token)
        # Pause the current song
        curl -X PUT "https://api.spotify.com/v1/me/player/pause" -H "Accept: application/json" -H "Authorization: Bearer $token" -H "Content-Type: application/json" -H "Content-Length: 0"
        # Select my iPhone as device
        #curl -X GET "https://api.spotify.com/v1/me/player/devices" -H "Accept: application/json" -H "Authorization: Bearer $token"
        device=$(curl -X GET "https://api.spotify.com/v1/me/player/devices" -H "Accept: application/json" -H "Authorization: Bearer $token" | jq -r '.devices[] | select(.name == "F iPhone Xs") | .id')
        #echo $device
        curl -X "PUT" "https://api.spotify.com/v1/me/player" --data "{\"device_ids\":[\"${device}\"]}" -H "Accept: application/json" -H "Content-Type: application/json" -H "Authorization: Bearer $token"

fi

if [[ "$1" = "connect_airplay" ]]; then
        connectAirplay
fi

if [[ "$1" = "test_connection" ]]; then

        # Check if Token is new enough
        updateToken
        # Read token from file
        token=$(<./token)
        # Check connection to spotify
        status=$(curl -X GET "https://api.spotify.com/v1/me/player" -H "Accept: application/json" -H "Authorization: Bearer $token")
        curl -X GET "https://api.spotify.com/v1/me/player" -H "Accept: application/json" -H "Authorization: Bearer $token"
        echo $status
fi
